// Code generated by goctl. DO NOT EDIT.
package types

type ChatHistoryRequest struct {
	UserID   uint `header:"User-ID"`
	Page     int  `form:"page,optional"`
	Limit    int  `form:"limit,optional"`
	FriendID uint `form:"friendId"` // 好友id
}

type ChatHistoryResponse struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"userId"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"created_at"` // 消息时间
}

type ChatSessionRequest struct {
	UserID uint `header:"User-ID"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
	Key    int  `form:"key,optional"`
}

type ChatSession struct {
	UserID     uint   `json:"userId"`
	Avatar     string `json:"avatar"`
	Nickname   string `json:"nickname"`
	CreatedAt  string `json:"created_at"` // 消息时间
	MsgPreview string `json:"msgPreview"` // 消息预览
	IsTop      bool   `json:"isTop"`      // 是否置顶
}

type ChatSessionResponse struct {
	List  []ChatSession `json:"list"`
	Count int64         `json:"count"`
}

type UserTopRequest struct {
	UserID   uint `header:"User-ID"`
	FriendID uint `json:"friendId"` // 好友id
}

type UserTopResponse struct {
}

type ChatDeleteRequest struct {
	UserID uint   `header:"User-ID"`
	IdList []uint `json:"idList"`
}

type ChatDeleteResponse struct {
}

type ChatRequest struct {
	UserID uint `header:"User-ID"`
}

type ChatResponse struct {
}

type ChatAdminHistoryRequest struct {
	SendUserID uint `form:"sendUserId"`
	RevUserID  uint `form:"revUserId"`
	Page       int  `form:"page,optional"`
	Limit      int  `form:"limit,optional"`
}

type ChatAdminSessionRequest struct {
	RevUserID uint `form:"revUserId"`
}

type UserInfo struct {
	UserID   uint   `json:"userId"`
	Avatart  string `json:"avatart"`
	Nickname string `json:"nickname"`
}

type ChatAdminSessionResponse struct {
	List  []UserInfo `json:"list"`
	Count int        `json:"count"`
}

type ChatAdminHistoryRemoveRequest struct {
	IdList []uint `json:"idList"`
}

type ChatAdminHistoryRemoveResponse struct {
}
