Name: group
Host: 0.0.0.0
Port: 20024
Mysql:
  DataSource: root:root@tcp(10.0.0.20:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local
Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Stat: false
Etcd: 10.0.0.22:2379
Redis:
  Addr: 10.0.0.21:6379
  Pwd:
  DB: 0
UserRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: userrpc.rpc
GroupRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: grouprpc.rpc