// Code generated by goctl. DO NOT EDIT.
package types

type OpenLoginInfoResponse struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	Href string `json:"href"` // 跳转地址
}

type SettingsInfoRequest struct {
}

type SettingsInfoResponse struct {
}

type SettingsInfoUpdateRequest struct {
}

type SettingsInfoUpdateResponse struct {
}
