Name: settings
Host: 0.0.0.0
Port: 20026
Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Stat: false
Etcd: 10.0.0.22:2379
Mysql:
  DataSource: root:root@tcp(10.0.0.20:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local
OpenLoginList:
  - name: QQ登录
    icon: https://www.fengfengzhidao.com/image/icon/qq.png
    href: https://graph.qq.com/oauth2.0/show?which=Login&display=pc&response_type=code&client_id=101974593&redirect_uri=http://www.fengfengzhidao.com/login?flag=qq
