Name: auth
Host: 0.0.0.0
Port: 20021
Mysql:
  DataSource: root:root@tcp(10.0.0.20:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local
Auth:
  AccessSecret: dfff1234
  AccessExpire: 3600
Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Stat: false
Redis:
  Addr: 10.0.0.21:6379
  Pwd:
  DB: 0
Etcd: 10.0.0.22:2379
OpenLoginList:
  - name: QQ登录
    icon: https://www.fengfengzhidao.com/image/icon/qq.png
    href: https://graph.qq.com/oauth2.0/show?which=Login&display=pc&response_type=code&client_id=101974593&redirect_uri=http://www.fengfengzhidao.com/login?flag=qq
UserRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: userrpc.rpc
SettingsRpc:
  Etcd:
    Hosts:
      - 10.0.0.22:2379
    Key: settingsrpc.rpc
WhiteList:
  - /api/auth/login
  - /api/auth/open_login
  - /api/auth/authentication
  - /api/auth/logout
  - /api/file/.{8}-.{4}-.{4}-.{4}-.{12}
  - /api/settings/open_login
  - /api/settings/info
KqPusherConf:
  Brokers:
    - 10.0.0.24:9092
  Topic: log-topic