// Code generated by goctl. DO NOT EDIT.
package types

type VerificationQuestion struct {
	Problem1 *string `json:"problem1,optional" user_conf:"problem1"`
	Problem2 *string `json:"problem2,optional" user_conf:"problem2"`
	Problem3 *string `json:"problem3,optional" user_conf:"problem3"`
	Answer1  *string `json:"answer1,optional" user_conf:"answer1"`
	Answer2  *string `json:"answer2,optional" user_conf:"answer2"`
	Answer3  *string `json:"answer3,optional" user_conf:"answer3"`
}

type UserInfoRequest struct {
	UserID uint `header:"User-ID"`
	Role   int8 `header:"Role"`
}

type UserInfoResponse struct {
	UserID               uint                  `json:"userID"`
	Nickname             string                `json:"nickname"`
	Abstract             string                `json:"abstract"`
	Avatar               string                `json:"avatar"`
	RecallMessage        *string               `json:"recallMessage"`
	FriendOnline         bool                  `json:"friendOnline"`
	Sound                bool                  `json:"sound"`
	SecureLink           bool                  `json:"secureLink"`
	SavePwd              bool                  `json:"savePwd"`
	SearchUser           int8                  `json:"searchUser"`
	Verification         int8                  `json:"verification"`
	VerificationQuestion *VerificationQuestion `json:"verificationQuestion"`
}

type UserInfoUpdateRequest struct {
	UserID               uint                  `header:"User-ID"`
	Nickname             *string               `json:"nickname,optional" user:"nickname"`
	Abstract             *string               `json:"abstract,optional" user:"abstract"`
	Avatar               *string               `json:"avatar,optional" user:"avatar"`
	RecallMessage        *string               `json:"recallMessage,optional" user_conf:"recall_message"`
	FriendOnline         *bool                 `json:"friendOnline,optional" user_conf:"friend_online"`
	Sound                *bool                 `json:"sound,optional" user_conf:"sound"`
	SecureLink           *bool                 `json:"secureLink,optional" user_conf:"secure_link"`
	SavePwd              *bool                 `json:"savePwd,optional" user_conf:"save_pwd"`
	SearchUser           *int8                 `json:"searchUser,optional" user_conf:"search_user"`
	Verification         *int8                 `json:"verification,optional" user_conf:"verification"`
	VerificationQuestion *VerificationQuestion `json:"verificationQuestion,optional" user_conf:"verification_question"`
}

type UserInfoUpdateResponse struct {
}

type FriendInfoRequest struct {
	UserID   uint `header:"User-ID"`
	Role     int8 `header:"Role"`
	FriendID uint `form:"friendID"` // 好友的用户id
}

type FriendInfoResponse struct {
	UserID   uint   `json:"userID"`
	Nickname string `json:"nickname"`
	Abstract string `json:"abstract"`
	Avatar   string `json:"avatar"`
	Notice   string `json:"notice"`
	IsOnline bool   `json:"isOnline"` // 是否在线
}

type FriendListRequest struct {
	UserID uint `header:"User-ID"`
	Role   int8 `header:"Role"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
}

type FriendListResponse struct {
	List  []FriendInfoResponse `json:"list"`
	Count int                  `json:"count"`
}

type FriendNoticeUpdateRequest struct {
	UserID   uint   `header:"User-ID"`
	FriendID uint   `json:"friendID"`
	Notice   string `json:"notice"` // 备注
}

type FriendNoticeUpdateResponse struct {
}

type SearchRequest struct {
	UserID uint   `header:"User-ID"`
	Key    string `form:"key,optional"`    // 用户id和昵称
	Online bool   `form:"online,optional"` // 搜索在线的用户
	Page   int    `form:"page,optional"`
	Limit  int    `form:"limit,optional"`
}

type SearchInfo struct {
	UserID   uint   `json:"userID"`
	Nickname string `json:"nickname"`
	Abstract string `json:"abstract"`
	Avatar   string `json:"avatar"`
	IsFriend bool   `json:"isFriend"` // 是否是好友
}

type SearchResponse struct {
	List  []SearchInfo `json:"list"`
	Count int64        `json:"count"`
}

type UserValidRequest struct {
	UserID   uint `header:"User-ID"`
	FriendID uint `json:"friendId"`
}

type UserValidResponse struct {
	Verification         int8                 `json:"verification"`         // 好友验证
	VerificationQuestion VerificationQuestion `json:"verificationQuestion"` // 问题和答案，但是答案不要返回
}

type AddFriendRequest struct {
	UserID               uint                  `header:"User-ID"`
	FriendID             uint                  `json:"friendId"`
	Verify               string                `json:"verify,optional"`               // 验证消息
	VerificationQuestion *VerificationQuestion `json:"verificationQuestion,optional"` // 问题和答案
}

type AddFriendResponse struct {
}

type FriendValidRequest struct {
	UserID uint `header:"User-ID"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
}

type FriendValidInfo struct {
	UserID               uint                  `json:"userID"`
	Nickname             string                `json:"nickname"`
	Avatar               string                `json:"avatar"`
	AdditionalMessages   string                `json:"additionalMessages"`   // 附加消息
	VerificationQuestion *VerificationQuestion `json:"verificationQuestion"` // 验证问题  为3和4的时候需要
	Status               int8                  `json:"status"`               // 状态 0 未操作 1 同意 2 拒绝 3 忽略
	SendStatus           int8                  `json:"sendStatus"`           // 状态 0 未操作 1 同意 2 拒绝 3 忽略
	RevStatus            int8                  `json:"revStatus"`            // 状态 0 未操作 1 同意 2 拒绝 3 忽略
	Verification         int8                  `json:"verification"`         // 好友验证
	ID                   uint                  `json:"id"`                   // 验证记录的id
	Flag                 string                `json:"flag"`                 // send 我是发起方  rev 我是接收方
	CreatedAt            string                `json:"createdAt"`            // 验证的时间
}

type FriendValidResponse struct {
	List  []FriendValidInfo `json:"list"`
	Count int64             `json:"count"`
}

type FriendValidStatusRequest struct {
	UserID   uint `header:"User-ID"`
	VerifyID uint `json:"verifyId"`
	Status   int8 `json:"status"` // 状态
}

type FriendValidStatusResponse struct {
}

type FriendDeleteRequest struct {
	UserID   uint `header:"User-ID"`
	FriendID uint `json:"friendId"`
}

type FriendDeleteResponse struct {
}

type UserListRequest struct {
	Key   string `form:"key,optional"` // 用户id和昵称
	Page  int    `form:"page,optional"`
	Limit int    `form:"limit,optional"`
}

type UserListInfoResponse struct {
	ID                 uint   `json:"id"`
	CreatedAt          string `json:"createdAt"`
	Nickname           string `json:"nickname"`
	Avatar             string `json:"avatar"`
	IP                 string `json:"ip"`
	Addr               string `json:"addr"`
	IsOnline           bool   `json:"isOnline"`
	SendMsgCount       int    `json:"sendMsgCount"`       // 发送消息个数
	GroupAdminCount    int    `json:"groupAdminCount"`    // 建群数量
	GroupCount         int    `json:"groupCount"`         // 进群数量
	CurtailChat        bool   `json:"curtailChat"`        // 限制聊天
	CurtailAddUser     bool   `json:"curtailAddUser"`     // 限制加人
	CurtailCreateGroup bool   `json:"curtailCreateGroup"` // 限制建群
	CurtailInGroupChat bool   `json:"curtailInGroupChat"` // 限制加群
}

type UserListResponse struct {
	List  []UserListInfoResponse `json:"list"`
	Count int64                  `json:"count"`
}

type UserCurtailRequest struct {
	UserID             uint `json:"userId"`             // 限制的用户
	CurtailChat        bool `json:"curtailChat"`        // 限制聊天
	CurtailAddUser     bool `json:"curtailAddUser"`     // 限制加人
	CurtailCreateGroup bool `json:"curtailCreateGroup"` // 限制建群
	CurtailInGroupChat bool `json:"curtailInGroupChat"` // 限制加群
}

type UserCurtailResponse struct {
}

type UserDeleteRequest struct {
	IdList []uint `json:"idList"`
}

type UserDeleteResponse struct {
}
