Name: userrpc.rpc
ListenOn: 0.0.0.0:30021
Etcd:
  Hosts:
    - 10.0.0.22:2379
  Key: userrpc.rpc
Mysql:
  DataSource: root:root@tcp(10.0.0.20:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local
Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Stat: false
RedisConf:
  Addr: 10.0.0.21:6379
  Pwd:
  DB: 0